### Why Handle Missing Values?
#### Missing values can arise due to data collection errors, system failures, or incomplete responses. If left unaddressed, they can lead to biased conclusions and poor model performance.

### Methods for Handling Missing Values
### There are several ways to handle missing values:

### Removing Data
### Removing columns with too many missing values.
### Removing rows that contain missing values.
### Filling Missing Values (Imputation)
#### For numerical data: Use mean, median, or mode.
#### For categorical data: Use mode or introduce a new category.
#### Advanced Imputation Techniques
#### Interpolation to estimate missing values.
#### Predictive models to estimate missing values based on other variables.

In [33]:
import pandas as pd

In [34]:
import numpy as np

In [35]:
data=pd.read_csv("googleplaystore.csv")

## handiling missing values

In [36]:
data.head()
#df.head(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [37]:
data.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [38]:
df=data.dropna()
#pd.read_csv("googleplaystore.csv").dropna()

# Numeric data
### similarly do the same for every column in dataset

In [39]:
count = 0
for i in df['Rating']:
    count+=i
print(count)

39235.60000000005

In [40]:
df['Rating']

0        4.1
1        3.9
2        4.7
3        4.5
4        4.3
        ...
10834    4.0
10836    4.5
10837    5.0
10839    4.5
10840    4.5
Name: Rating, Length: 9360, dtype: float64

In [42]:
int(sum(df['Rating']))

39235

In [41]:
sum(df['Rating'])

39235.6

### for average rating we need given sum  by total

In [44]:
avg_rating = int(sum(df['Rating']))/9360
print(avg_rating)

4.191773504273504

# "Categorie Data"
#### similarly do for every category data column

In [45]:
df.Category

0             ART_AND_DESIGN
1             ART_AND_DESIGN
2             ART_AND_DESIGN
3             ART_AND_DESIGN
4             ART_AND_DESIGN
                ...
10834                 FAMILY
10836                 FAMILY
10837                 FAMILY
10839    BOOKS_AND_REFERENCE
10840              LIFESTYLE
Name: Category, Length: 9360, dtype: object

In [49]:
df['Category'].unique()

array(['ART_AND_DESIGN', 'AUTO_AND_VEHICLES', 'BEAUTY',
       'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION',
       'DATING', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS', 'FINANCE',
       'FOOD_AND_DRINK', 'HEALTH_AND_FITNESS', 'HOUSE_AND_HOME',
       'LIBRARIES_AND_DEMO', 'LIFESTYLE', 'GAME', 'FAMILY', 'MEDICAL',
       'SOCIAL', 'SHOPPING', 'PHOTOGRAPHY', 'SPORTS', 'TRAVEL_AND_LOCAL',
       'TOOLS', 'PERSONALIZATION', 'PRODUCTIVITY', 'PARENTING', 'WEATHER',
       'VIDEO_PLAYERS', 'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION'],
      dtype=object)

### to know the count of each categorytype in category column

In [55]:
count = 0
for i in df['Category']:
    if(i=='ART_AND_DESIGN'):
        count+=1
print('ART_AND_DESIGN',count)

ART_AND_DESIGN 61

In [56]:
count = 0
for i in df['Category']:
    if(i=='BUSINESS'):
        count+=1
print('BUSINESS',count)

BUSINESS 303

### to avoid manual count for each category @2 methods
#### -run for loop for each categorytype to the given column
#### *create a dictory to store each caterogy count
#### *run for loop for each unique category
#### *count the items for each categorytype
#### store in dictonary

In [61]:
categories = {}
for name in df['Category'].unique():
    count = 0
    for i in df['Category']:
        if(i == name):
            count+=1
        categories[name] = count
            
print(categories)

{'ART_AND_DESIGN': 61, 'AUTO_AND_VEHICLES': 73, 'BEAUTY': 42, 'BOOKS_AND_REFERENCE': 178, 'BUSINESS': 303, 'COMICS': 58, 'COMMUNICATION': 328, 'DATING': 195, 'EDUCATION': 155, 'ENTERTAINMENT': 149, 'EVENTS': 45, 'FINANCE': 323, 'FOOD_AND_DRINK': 109, 'HEALTH_AND_FITNESS': 297, 'HOUSE_AND_HOME': 76, 'LIBRARIES_AND_DEMO': 64, 'LIFESTYLE': 314, 'GAME': 1097, 'FAMILY': 1746, 'MEDICAL': 350, 'SOCIAL': 259, 'SHOPPING': 238, 'PHOTOGRAPHY': 317, 'SPORTS': 319, 'TRAVEL_AND_LOCAL': 226, 'TOOLS': 733, 'PERSONALIZATION': 312, 'PRODUCTIVITY': 351, 'PARENTING': 50, 'WEATHER': 75, 'VIDEO_PLAYERS': 160, 'NEWS_AND_MAGAZINES': 233, 'MAPS_AND_NAVIGATION': 124}

In [62]:
for name in df['Category'].unique():
    count = 0
    for i in df['Category']:
        if(i == name):
            count+=1
    print(name,":",count)

ART_AND_DESIGN : 61
AUTO_AND_VEHICLES : 73
BEAUTY : 42
BOOKS_AND_REFERENCE : 178
BUSINESS : 303
COMICS : 58
COMMUNICATION : 328
DATING : 195
EDUCATION : 155
ENTERTAINMENT : 149
EVENTS : 45
FINANCE : 323
FOOD_AND_DRINK : 109
HEALTH_AND_FITNESS : 297
HOUSE_AND_HOME : 76
LIBRARIES_AND_DEMO : 64
LIFESTYLE : 314
GAME : 1097
FAMILY : 1746
MEDICAL : 350
SOCIAL : 259
SHOPPING : 238
PHOTOGRAPHY : 317
SPORTS : 319
TRAVEL_AND_LOCAL : 226
TOOLS : 733
PERSONALIZATION : 312
PRODUCTIVITY : 351
PARENTING : 50
WEATHER : 75
VIDEO_PLAYERS : 160
NEWS_AND_MAGAZINES : 233
MAPS_AND_NAVIGATION : 124

### shortcut to know the no of categories and popular category in column
#### count       9360 ---> total rows in column category
#### unique        33----> no of categories in column
#### top       FAMILY-------> popular category
#### freq        1746-------> freq of popular category(family)
#### Name: Category, dtype: object

In [64]:
df['Category'].describe()

count       9360
unique        33
top       FAMILY
freq        1746
Name: Category, dtype: object

## "Analysis on multiple Columns"

##### dataset to array
##### Here we may deal with multiple different tyes of categoris we need the dataframe into category

In [79]:
#Here we may deal with multiple different tyes of categoris we need the dataframe into category
ar=df.values
ar

array([['Photo Editor & Candy Camera & Grid & ScrapBook',
        'ART_AND_DESIGN', 4.1, ..., 'January 7, 2018', '1.0.0',
        '4.0.3 and up'],
       ['Coloring book moana', 'ART_AND_DESIGN', 3.9, ...,
        'January 15, 2018', '2.0.0', '4.0.3 and up'],
       ['U Launcher Lite – FREE Live Cool Themes, Hide Apps',
        'ART_AND_DESIGN', 4.7, ..., 'August 1, 2018', '1.2.4',
        '4.0.3 and up'],
       ...,
       ['Fr. Mike Schmitz Audio Teachings', 'FAMILY', 5.0, ...,
        'July 6, 2018', '1.0', '4.1 and up'],
       ['The SCP Foundation DB fr nn5n', 'BOOKS_AND_REFERENCE', 4.5, ...,
        'January 19, 2015', 'Varies with device', 'Varies with device'],
       ['iHoroscope - 2018 Daily Horoscope & Astrology', 'LIFESTYLE',
        4.5, ..., 'July 25, 2018', 'Varies with device',
        'Varies with device']], dtype=object)

In [81]:
df.values.shape

(9360, 13)

### Q-how many  free apps are there in ART_AND_DESIGN

In [83]:
count = 0
for i in ar:
    if(i[1]=='ART_AND_DESIGN' and i[6]=='Free'):
        count+=1;
print("how many free apps are there in ART_AND_DESIGN: ",count)

how many free apps are there in ART_AND_DESIGN:  58

### Q-how many free apps are there in ART_AND_DESIGN

In [85]:
count = 0
for i in ar:
    if(i[1]=='ART_AND_DESIGN' and i[6]=='Paid'):
        count+=1;
print("how many Paid apps are there in ART_AND_DESIGN: ",count)

how many Paid apps are there in ART_AND_DESIGN:  3

### Q-how may apps are there in ART_AND_DESIGN with rating more than 4.5

In [94]:
count = 0
for i in ar:
    if(i[1]=='ART_AND_DESIGN' and i[2]>= 4.5):
        count+=1;
print("how may apps are there in ART_AND_DESIGN with rating more than 4.5: ",count)

how may apps are there in ART_AND_DESIGN with rating more than 4.5:  26

### Q-how may apps are there in family category with rating more than 4.5 and should be free

In [90]:
count = 0
for i in ar:
    if(i[1]=='FAMILY' and i[6]== 'Free' and i[2]>= 4.5):
        count+=1;
print("how may apps are there in family category with rating more than 4.5 and should be free: ",count)

how may apps are there in family category with rating more than 4.5 and should be free:  477

### Q-list all the free apps with rating more than 4.5 and should of family category

In [95]:
print("-"*150)
print("Q-list all the free apps with rating more than 4.5 and should of family category")
print("-"*150)
count = 0
for i in ar:
    if(i[1]=='FAMILY' and i[6]== 'Free' and i[2]>= 4.5):
        count+=1;
        print(i[0])

------------------------------------------------------------------------------------------------------------------------------------------------------
Q-list all the free apps with rating more than 4.5 and should of family category
------------------------------------------------------------------------------------------------------------------------------------------------------
YouTube Kids
ROBLOX
Mahjong
Super ABC! Learning games for kids! Preschool apps
Toy Pop Cubes
Candy Pop Story
Princess Coloring Book
Candy Smash
Happy Fruits Bomb - Cube Blast
Dog Run - Pet Dog Simulator
Puzzle Kids - Animals Shapes and Jigsaw Puzzles
Kids Educational :All in One
Toca Kitchen 2
No. Color - Color by Number, Number Coloring
Garden Fruit Legend
Candy Day
Learn To Draw Glow Princess
ABC Kids - Tracing & Phonics
Minion Rush: Despicable Me Official Game
Piano Kids - Music & Songs
Farming Simulator 14
Educational Games for Kids
No.Draw - Colors by Number 2018
Duolingo: Learn Languages Free
Hot Wheels: Race Off
Baby Tiger Care - My Cute Virtual Pet Friend
Kiddopia - Preschool Learning Games
Super ABC! Learning games for kids! Preschool apps
Drawing for Kids Learning Games for Toddlers age 3
Baby Panda’s Juice Shop
LEGO® Friends: Heartlake Rush
Baby ABC in box! Kids alphabet games for toddlers!
Henry Danger Crime Warp
Super School: Educational Kids Games & Rhymes
Fruit Cube Blast
Toddler Kids Puzzles PUZZINGO
Happy Street
Leo and Tig
Fuzzy Seasons: Animal Forest
Kids Corner: Interactive Tales and Games for kids
ROBLOX
Minion Rush: Despicable Me Official Game
Dog Run - Pet Dog Simulator
Hot Wheels: Race Off
Basketball FRVR - Shoot the Hoop and Slam Dunk!
Farming Simulator 14
My Oasis - Calming and Relaxing Idle Clicker Game
Cars: Lightning League
Pony Friends 🦄 - Beepzz racing game for kids
Ninja Dash - Ronin Jump RPG
Robots Vs Zombies: Transform To Race And Fight
Disney Crossy Road
Toca Kitchen 2
Monster High™ Minis Mania
Monica Toy TV
Sworkit Kids - Fitness Meets Fun
Crazy Colors: Bubbles Matching
Pino chess
All-in-One Mahjong 3 FREE
ROBLOX
YouTube Kids
Duolingo: Learn Languages Free
Animal Jam - Play Wild!
Real Racing 3
Dog Sim Online: Raise a Family
Color by Number - Draw Sandbox Pixel Art
Build a Bridge!
Find a Way: Addictive Puzzle
My Talking Tom
CompTIA Exam Training
My Talking Angela
YouTube Kids
Colorfy: Coloring Book for Adults - Free
Toca Kitchen 2
Gymnastics Superstar - Spin your way to gold!
Hungry Hearts Diner: A Tale of Star-Crossed Souls
Dragon Sim Online: Be A Dragon
Cat Sim Online: Play with Cats
Block Craft 3D: Building Simulator Games For Free
Hay Day
Block! Hexa Puzzle™
Clash of Clans
Clash Royale
Learn C [NEW]
Learn C++
C Programming Zone
All C Programs
C Programming - Learn Code, Theory & Discuss
codeEazy - C/C++/JAVA
C Pattern Programs Free
C Functions
Learn Basic C - For Beginners
C Prowess
101 C Programming Problems
C BOOK-C PROGRAMS
Minion Rush: Despicable Me Official Game
Block City Wars + skins export
Eternium
WWE
My Android Device S/W & H/W
Harris J Lyrics
2048 BTS J Hope KPop Puzzle Game
J. Cole Albums (2007-2017)
Radio K - KUOM
K-Otic Universe
CASE K-12 Math English Science
K-Spapp, the K-Space app
EXO-L
French to English Speaking - Apprendre l' Anglais
Fantastic Chefs: Match 'n Cook
ROBLOX
Twitch: Livestream Multiplayer Games & Esports
U-Dictionary: Best English Learning Dictionary
Channel U
Get Free V-bucks_fortnite Hints
Easy V-Bux free
The X-Files: Deep State - Hidden Object Adventure
X-Wing Squadron Builder
JW Caleb y Sofia
PewDiePie's Tuber Simulator
War Z 2
Z-Empire: Dead Strike
Angry Birds Blast
Angry Birds Evolution
Angry Birds Match
Angry Birds POP Bubble Shooter
Angry Birds 2
Angry Birds Epic RPG
Ad-free Triangle Solver
Alchemy Classic Ad Free
Nasihat - Chalo ae Pyaara
9GAG: Funny Gifs, Pics, Memes & Videos for IGTV
Denis Brogniart - AH !
Replika
Orbita AI — Exciting mobile puzzles & riddles
Learn Artificial Intelligence
Animal Jam - Play Wild!
AJ Academy: Amazing Animals
Dash Tag - Fun Endless Runner!
AJ Official
Little Pets Animal Guardians
My Wild Pet: Online Animal Sim
AJ Rafael Music Lessons
Weapon stripping 3D
University of Alabama
Al jazeera TV
Al Quran Audio (Full 30 Juz)
Quran for All (Al-Huda Int.)
Ayat - Al Quran
Quran Juz-30 - Mahad al Zahra
Al-Quran Al-Muallim
Al Quran MP3 - Quran Reading®
Al-Quran Ahmad Saud Offline
My Horse
Virtual lover
Princess Closet : Otome games free dating sim
virtual lover 3D
Bubbu – My Virtual Pet
AP® Guide
AP Mobile
AP English Language: Practice Tests and Flashcards
Study AP World History
AP Chemistry Prep: Practice Tests and Flashcards
AP World History: Practice Tests and Flashcards
AP Biology Prep: Practice Tests, Flashcards
AP Psychology Prep: Practice Tests and Flashcards
AP European History: Practice Tests and Flashcards
Adventure Quest World Mobile Quiz
Aqw&3d Design Notes Manager
AQ Ria Retail
Accounting Quiz (AQ) Malaysia
Wowkwis aq Ka'qaquj
Questland: Turn Based RPG
Dungeon Quest
Grow Stone Online : 2d pixel RPG, MMORPG game
Egg, Inc.
AR Toys: Playground Sandbox | Remote Car
Choices: Stories You Play
Seen
STUCOR - AU
Aw Restaurant
AW Training
Anime Expo 2018
INTERACTIVE CALCULUS FOR MATHS AND PHYSICS
Ay Up
Pinoy Kid Song Ako ay may Lobo
Quran Khmer Offline AY
Permit Test AZ Arizona MVD DOT
Catalyst AZ
Az Video Status
Ultrasound A-Z
Goody.ba
Learn alif ba ta
Arabic Alif Ba Ta For Kids
Arabic Alphabet Alif Ba Ta Wooden Blocks
Let's Learn Alif Ba Ta
Sufara.ba
Elif Ba - Learn The Holy Quran
Alif Ba Ta Song - Arabic Kids
Elifba Quran Learning Game
Railroad Radio Vancouver BC
BD Online Passport Application
BD Hospital's
Exam Result BD
The Sims™ Mobile
OK K.O.! Lakewood Plaza Turbo
BG Future School
Learn Bulgarian Free
Bh Public School
BH Challenge - Museum of the Jewish People
Bitmoji – Your Personal Emoji
Business Intelligence & Data
TED
Learn English Vocabulary - 6,000 Words
English Grammar Test
HON. B.J. ACS COLLEGE ALE
BK Video Status
Audio Murli Glossary For BK
Baba Yaad Hai?(BK's)
BK murli today (Mobile Murli) - Gyan
BK Murli Dictionary (H to E)
BkEmu - BK-0010/11M emulator
Cerulean Heart
あなカレ【BL】無料ゲーム
OTOME of Ikemen cafe
BM SPM Practice
Bubble Bo-Bo
Boom Beach
Township
Go-Go-Goat! Free Game
Blood Pressure Diary
RoboPad
Zowi App
Left vs Right: Brain Training
Br. Parking - Busy road Parking 3D 2018
Br Shafi
Companion for Fortnite & Fortnite Battle Royale
Vlogger Go Viral - Tuber Game
Loved by King Bs
BS CS IT & SE
Marked by King Bs
COMSATS BOOK STORE FOR BS(CS)
Beauty Rental Shop
Bsc Agri Notes
Sleeping Delivery
Wifi BT Scanner
BU Study
BU Mobile
Barisal University App-BU Face
Pu - Cute giant panda bear, baby pet care game
BU Students' Rep. Council
BU Calculator
BU Syllabus
BV Sridhara Maharaj
Quadratic Equation Solver with Steps and Graphs
Sandbox - Color by Number Coloring Pages
Sandbox Art-Sandbox Color by Number Coloring Pages
Art Pixel Coloring. Color by Number.
Color By Number - Sandbox Pixel Coloring Book
PixelDot - Color by Number Sandbox Pixel Art
PixPanda - Color by Number Pixel Art Coloring Book
PixBox Coloring - Color by number Sandbox
Pixyfy: coloring by number coloring book
Draw Color by Number - Sandbox Pixel Art
3D Color by Number with Voxels
Butterfly Pixel Art - coloring by number
Pixel art pro-Sand box,paint by number,number draw
Color by Number: Pixel Art
UNICORN - Color By Number & Pixel Art Coloring
FunnyPixels - Color by number Sandbox
No.Diamond – Colors by Number
Park Limousine: Realistic Limo Parking Simulator
CB News
CB Register
CD CHOICE TUBE
Yazdani Cd Center EllahAbad Official App
CEHQ - CE Credits for Nurses
MCQ CE IT
Magana Jari ce Littafi Na Uku : Part 3 of 3
CF Life
All Info about Cg
cg guruji
CG Wallpapers
CG FM
CG - Chemistry free
CG Jobs
BF CG Abstract Pictures
waut.ch!
CI Dictionary
SimCity BuildIt
CJ SO COOL
Sir C J New Primary School
Louis CK
Tic Tac CK
Castle Clash: Heroes of the Empire US
CN Sayin' - Cartoon Network
Cartoon Network Match Land
Super Slime Blitz - Gumball
Surely You Quest - Magiswords
We Bare Bears Match3 Repairs
Champions and Challengers - Adventure Time
What's Up, Snoopy? - Peanuts
CN Resident
Dots & Co: A Puzzle Adventure
Permit Test CO Colorado DMV
CP Channel
Foothills CP
Cp Calculator for Evolution:GO
ClanManagerTT2
Christian Questions Podcast
الفاتحون Conquerors
CR & CoC Private Server - Clash Barbarians PRO
Ultimate Clash Royale Tracker
Servidor Privado de CR y CoC - Light Royale
Deck Shop for Clash Royale
Cr Aviation Academy
CS Interview Questions (TechQ)
DU CS Lectures - Learn to Code for Free
CS & IT Interview Questions
CA CS Network
CT Scan Generations
CT Brain Interpretation
Permit Test Connecticut CT DMV
Results for CT Lottery
CV Examples 2018
CW Seed
FANDOM: Arrow and The Flash
CX watcher
Cy-Reader
Igitabo cy'Indirimbo
Cymath - Math Problem Solver
Army of Heroes
MadLipz
DB Tools
DB for Hustle Castle
DC Legends: Battle for Justice
MARVEL Future Fight
DC N COMPANY ENTERTAINMENT RADIO!
Driver Permit Test Prep DC DMV Driver's License Ed
Coloring Book for Me & Mandala
Anime Love Story Games: ✨Shadowtime✨
DH-UFO
Idle Heroes
Pocket Heroes
Duolingo: Learn Languages Free
Account Class-11 Solutions (D K Goel)
PK and DK Audio App
dk
Account Class-12 Solutions (D K Goel) Vol-2
DL Hughley
DM Buddy » Learn Digital Marketing
Disciple Maker’s (DM) Lab
DN Employee
Dragon Nest M
Downtown Mafia: Gang Wars (Mobster Game) Free
Guardian Hunter: SuperBrawlRPG
CritDice - Dice Roller
Maher EL Mouaikly - Offline
Darkness Rises
DO YOU KNOW THE WAY Soundboard
Latest DP and Status Pro 2018
DP Battle
Faceoff DP Battle App
RPG Dragon Lapis
DQSalmaan - A fan made App
Dr. Cares - Amy's Pet Clinic 🐈 🐕
DS
MegaN64 (N64 Emulator)
DS-Students
DT Driving Test Theory
WPBS-DT
Du Chinese – Mandarin Lessons
DV-LOTTERY 2019 REGISTRATION
DV ASSIST
DV Lottery Simulator
U.S.A DV Lottery Process
DV-2019 UK/British
DW Audio
German Listening
Piczle Lines DX
DX Simulation for OOO Dx Belt
DX Simulation Belt for Build henshin
DX Simulation for Kabuto Henshin Belt 2018
DX Simulation for Double Dx Henshin Belt 2018
DX Simulation Belt for Decade henshin
KPS CHAUHAN DY/DX
DYPSOET
Real Racing 3
Madden NFL Football
Star Wars™: Galaxy of Heroes
Bejeweled Stars: Free Match 3
Typical EA Game
My Handbook : EE, EC, EI, E&T, EEE, EECS
EC Calgary
EC Fairgrounds
GATE Syllabus for EC 2018 & Notifications
English Conversation Courses
Fashion Pony Girls Dress Up Makeup Game
Dance Magic Fashion Style Games
Instant Buttons: The Best Soundboard
Disaster Will Strike
EI国际
TeamWard – live help for LoL
Master E.K
Ek Onkar
Pyaar Ek Dhoka
Ringtones Of Ek Onkar
Ek Kahani Aisi Bhi Season 2 - The Horror Story
Ek Bander Ne Kholi Dukan
Toilet Ek Prem Katha Songs Lyrics in Hindi
Sanu Ek Pal Chain Song Videos - RAID Movie Songs
Ek Qissa He Quran Se (Qurani Waqiyat)
Lyrics of Ek Paheli Leela
Exiled Kingdoms RPG
Shabad Gurubani Punjabi mp3 free - Ek Onkar Satnam
El Falı
OWLIE BOO
Narcos: Cartel Wars
Connect'Em
Connect'Em Halloween
Hello English: Learn English
Learn English Daily
Learn Top 300 English Words
Masha and the Bear: Evolution
Masha and the Bear. Games for kids
Masha and The Bear Jam Day Match 3 games for kids
Masha and the Bear: House Cleaning Games for Girls
Masha and the Bear. Educational Games
Masha and the Bear: Good Night!
Masha and the Bear: Climb Racing and Car Games
EP Radio
Noot-Noot-er!
Super Doctor 2 - My Newborn Baby ER Injection
Doctor Games For Girls - Hospital ER
Open Heart Surgery Hospital ER: Crazy Doctor Sim
YEBIS OpenGL ES 3.0 Tech Demo
Advanced calculator fx 991 es plus & 991 ms plus
Castle Clash: Epic Empire ES
School scientific calculator fx 500 es plus 500 ms
Esto Es Guerra TVN
Lettre et demande d'emploi
Pocket Mortys
Invasive Alien Species Europe
daskal.eu
PokeType - Dex
Raytheon F-16 EW 360 VR
TRANSFORMERS: Earth Wars
Pink Guy - Ey B0ss
Ey Sey Storytime រឿងនិទានតាឥសី
Fallout Shelter
Who viewed my fb profile pro★★
Story Time FD
FD VR Music Videos - MTV Pop and Rap in 360
Fire Emblem Heroes
Safe Santa Fe
POLARIS 2MFG
Family Guy- Another Freakin' Mobile Game
Puzzles Volvo FH 16 Trucks
Jigsaw Volvo FH 16 Trucks
FH School
Driving n Parking School 2017
FK Željezničar Izzy
Permit Test FL Florida DHSMV
FL Lottery Results
Scratch-Off Guide for FL Lotto
Florida Driver License Test
Canvas FL
Florida Wildflowers
How it Works: FN SCAR assault rifle
Ninja FN Button
Pin-fo
FP Разбитый дисплей
Fr Ignacio Outreach
Castle Clash: RPG War and Strategy FR
Fr. Daoud Lamei
Sya9a Maroc - FR
Fr. Mike Schmitz Audio Teachings

# "Analysis of Dataset with Conditions"

In [98]:
#datarows belong to family in category column
df['Category']=="FAMILY"

0        False
1        False
2        False
3        False
4        False
         ...
10834     True
10836     True
10837     True
10839    False
10840    False
Name: Category, Length: 9360, dtype: bool

### Q-records with are of Family application category in category column

In [101]:
df[df['Category']=="FAMILY"]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2014,YouTube Kids,FAMILY,4.5,470694,Varies with device,"50,000,000+",Free,0,Everyone,Entertainment;Music & Video,"August 3, 2018",3.43.3,4.1 and up
2015,Candy Bomb,FAMILY,4.4,42145,20M,"10,000,000+",Free,0,Everyone,Casual;Brain Games,"July 4, 2018",2.9.3181,4.0.3 and up
2016,ROBLOX,FAMILY,4.5,4449910,67M,"100,000,000+",Free,0,Everyone 10+,Adventure;Action & Adventure,"July 31, 2018",2.347.225742,4.1 and up
2017,Jewels Crush- Match 3 Puzzle,FAMILY,4.4,14774,19M,"1,000,000+",Free,0,Everyone,Casual;Brain Games,"July 23, 2018",1.9.3901,4.0.3 and up
2018,Coloring & Learn,FAMILY,4.4,12753,51M,"5,000,000+",Free,0,Everyone,Educational;Creativity,"July 17, 2018",1.49,4.0.3 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10820,Fr. Daoud Lamei,FAMILY,5.0,22,8.6M,"1,000+",Free,0,Teen,Education,"June 27, 2018",3.8.0,4.1 and up
10827,Fr Agnel Ambarnath,FAMILY,4.2,117,13M,"5,000+",Free,0,Everyone,Education,"June 13, 2018",2.0.20,4.0.3 and up
10834,FR Calculator,FAMILY,4.0,7,2.6M,500+,Free,0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up

In [ ]:
### Q-how may free apps are avaliable in ART_AND_DESIGN

In [114]:
apps = df[df['Category']=="ART_AND_DESIGN"]
print(len(apps))
apps

61

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5258,AJ Styles Wallpaper 2018 - AJ Styles HD Wallpaper,ART_AND_DESIGN,4.0,18,3.6M,"1,000+",Free,0,Everyone,Art & Design,"March 22, 2018",1.1,4.0 and up
6930,Fantasy theme dark bw black building,ART_AND_DESIGN,4.8,41,1.9M,"5,000+",Free,0,Everyone,Art & Design,"March 20, 2018",1.0.2,4.0 and up
8679,Dp for girls,ART_AND_DESIGN,4.2,175,8.2M,"50,000+",Free,0,Everyone,Art & Design,"May 26, 2017",1.2,4.0.3 and up
8712,Name Art DP - Focus n Filter Text 2018,ART_AND_DESIGN,4.3,132,7.7M,"10,000+",Free,0,Everyone,Art & Design,"January 4, 2018",1,4.1 and up
8888,Spring flowers theme couleurs d t space,ART_AND_DESIGN,5.0,1,2.9M,100+,Free,0,Everyone,Art & Design,"April 18, 2018",1.0.2,4.0 and up

In [112]:
freeapps = apps[apps['Type']=='Free']
print("total free ART_AND_DESIGN apps",len(freeapps))
freeapps

total free ART_AND_DESIGN apps 58

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
5,Paper flowers instructions,ART_AND_DESIGN,4.4,167,5.6M,"50,000+",Free,0,Everyone,Art & Design,"March 26, 2017",1.0,2.3 and up
6,Smoke Effect Photo Maker - Smoke Editor,ART_AND_DESIGN,3.8,178,19M,"50,000+",Free,0,Everyone,Art & Design,"April 26, 2018",1.1,4.0.3 and up
7,Infinite Painter,ART_AND_DESIGN,4.1,36815,29M,"1,000,000+",Free,0,Everyone,Art & Design,"June 14, 2018",6.1.61.1,4.2 and up
8,Garden Coloring Book,ART_AND_DESIGN,4.4,13791,33M,"1,000,000+",Free,0,Everyone,Art & Design,"September 20, 2017",2.9.2,3.0 and up
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,121,3.1M,"10,000+",Free,0,Everyone,Art & Design;Creativity,"July 3, 2018",2.8,4.0.3 and up
10,Text on Photo - Fonteee,ART_AND_DESIGN,4.4,13880,28M,"1,000,000+",Free,0,Everyone,Art & Design,"October 27, 2017",1.0.4,4.1 and up
11,Name Art Photo Editor - Focus n Filters,ART_AND_DESIGN,4.4,8788,12M,"1,000,000+",Free,0,Everyone,Art & Design,"July 31, 2018",1.0.15,4.0 and up
12,Tattoo Name On My Photo Editor,ART_AND_DESIGN,4.2,44829,20M,"10,000,000+",Free,0,Teen,Art & Design,"April 2, 2018",3.8,4.1 and up
13,Mandala Coloring Book,ART_AND_DESIGN,4.6,4326,21M,"100,000+",Free,0,Everyone,Art & Design,"June 26, 2018",1.0.4,4.4 and up
14,3D Color Pixel by Number - Sandbox Art Coloring,ART_AND_DESIGN,4.4,1518,37M,"100,000+",Free,0,Everyone,Art & Design,"August 3, 2018",1.2.3,2.3 and up
16,Photo Designer - Write your name with shapes,ART_AND_DESIGN,4.7,3632,5.5M,"500,000+",Free,0,Everyone,Art & Design,"July 31, 2018",3.1,4.1 and up
17,350 Diy Room Decor Ideas,ART_AND_DESIGN,4.5,27,17M,"10,000+",Free,0,Everyone,Art & Design,"November 7, 2017",1.0,2.3 and up
18,FlipaClip - Cartoon animation,ART_AND_DESIGN,4.3,194216,39M,"5,000,000+",Free,0,Everyone,Art & Design,"August 3, 2018",2.2.5,4.0.3 and up
19,ibis Paint X,ART_AND_DESIGN,4.6,224399,31M,"10,000,000+",Free,0,Everyone,Art & Design,"July 30, 2018",5.5.4,4.1 and up
20,Logo Maker - Small Business,ART_AND_DESIGN,4.0,450,14M,"100,000+",Free,0,Everyone,Art & Design,"April 20, 2018",4.0,4.1 and up
21,Boys Photo Editor - Six Pack & Men's Suit,ART_AND_DESIGN,4.1,654,12M,"100,000+",Free,0,Everyone,Art & Design,"March 20, 2018",1.1,4.0.3 and up
22,Superheroes Wallpapers | 4K Backgrounds,ART_AND_DESIGN,4.7,7699,4.2M,"500,000+",Free,0,Everyone 10+,Art & Design,"July 12, 2018",2.2.6.2,4.0.3 and up
24,HD Mickey Minnie Wallpapers,ART_AND_DESIGN,4.7,118,23M,"50,000+",Free,0,Everyone,Art & Design,"July 7, 2018",1.1.3,4.1 and up
25,Harley Quinn wallpapers HD,ART_AND_DESIGN,4.8,192,6.0M,"10,000+",Free,0,Everyone,Art & Design,"April 25, 2018",1.5,3.0 and up
26,Colorfit - Drawing & Coloring,ART_AND_DESIGN,4.7,20260,25M,"500,000+",Free,0,Everyone,Art & Design;Creativity,"October 11, 2017",1.0.8,4.0.3 and up
27,Animated Photo Editor,ART_AND_DESIGN,4.1,203,6.1M,"100,000+",Free,0,Everyone,Art & Design,"March 21, 2018",1.03,4.0.3 and up
28,Pencil Sketch Drawing,ART_AND_DESIGN,3.9,136,4.6M,"10,000+",Free,0,Everyone,Art & Design,"July 12, 2018",6.0,2.3 and up
29,Easy Realistic Drawing Tutorial,ART_AND_DESIGN,4.1,223,4.2M,"100,000+",Free,0,Everyone,Art & Design,"August 22, 2017",1.0,2.3 and up
30,Pink Silver Bow Keyboard Theme,ART_AND_DESIGN,4.2,1120,9.2M,"100,000+",Free,0,Everyone,Art & Design,"July 12, 2018",6.7.12.2018,4.0.3 and up
31,Art Drawing Ideas,ART_AND_DESIGN,4.1,227,5.2M,"50,000+",Free,0,Everyone,Art & Design,"May 31, 2018",1.2,2.3 and up
32,Anime Manga Coloring Book,ART_AND_DESIGN,4.5,5035,11M,"100,000+",Free,0,Everyone,Art & Design,"July 19, 2018",2.20,4.0 and up
33,Easy Origami Ideas,ART_AND_DESIGN,4.2,1015,11M,"100,000+",Free,0,Everyone,Art & Design,"January 6, 2018",1.1.0,4.1 and up
34,I Creative Idea,ART_AND_DESIGN,4.7,353,4.2M,"10,000+",Free,0,Teen,Art & Design,"April 27, 2018",1.6,4.1 and up
35,How to draw Ladybug and Cat Noir,ART_AND_DESIGN,3.8,564,9.2M,"100,000+",Free,0,Everyone,Art & Design,"July 11, 2018",2.1,4.1 and up
36,UNICORN - Color By Number & Pixel Art Coloring,ART_AND_DESIGN,4.7,8145,24M,"500,000+",Free,0,Everyone,Art & Design;Creativity,"August 2, 2018",1.0.9,4.4 and up
37,Floor Plan Creator,ART_AND_DESIGN,4.1,36639,Varies with device,"5,000,000+",Free,0,Everyone,Art & Design,"July 14, 2018",Varies with device,2.3.3 and up
38,PIP Camera - PIP Collage Maker,ART_AND_DESIGN,4.7,158,11M,"10,000+",Free,0,Everyone,Art & Design,"November 29, 2017",1.3,4.0.3 and up
39,How To Color Disney Princess - Coloring Pages,ART_AND_DESIGN,4.0,591,9.4M,"500,000+",Free,0,Everyone,Art & Design,"March 31, 2018",1,4.0 and up
40,Drawing Clothes Fashion Ideas,ART_AND_DESIGN,4.2,117,15M,"10,000+",Free,0,Everyone,Art & Design,"July 20, 2018",2.0.1,4.0.3 and up
41,Sad Poetry Photo Frames 2018,ART_AND_DESIGN,4.5,176,10M,"100,000+",Free,0,Everyone,Art & Design,"April 2, 2018",1.0,4.0.3 and up
42,Textgram - write on photos,ART_AND_DESIGN,4.4,295221,Varies with device,"10,000,000+",Free,0,Everyone,Art & Design,"July 30, 2018",Varies with device,Varies with device
43,Paint Splash!,ART_AND_DESIGN,3.8,2206,1.2M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"April 15, 2018",1.46,4.1 and up
44,Popsicle Sticks and Similar DIY Craft Ideas,ART_AND_DESIGN,4.2,26,12M,"10,000+",Free,0,Everyone,Art & Design,"January 3, 2018",1.0.0,4.1 and up
45,"Canva: Poster, banner, card maker & graphic de...",ART_AND_DESIGN,4.7,174531,24M,"10,000,000+",Free,0,Everyone,Art & Design,"July 31, 2018",1.6.1,4.1 and up
46,Install images with music to make video withou...,ART_AND_DESIGN,4.6,1070,26M,"100,000+",Free,0,Everyone,Art & Design,"November 14, 2017",1.6,4.1 and up
47,Little Teddy Bear Colouring Book Game,ART_AND_DESIGN,4.2,85,8.0M,"100,000+",Free,0,Everyone,Art & Design,"December 17, 2017",2.0.0,4.1 and up
48,How To Draw Food,ART_AND_DESIGN,4.3,845,7.9M,"100,000+",Free,0,Everyone,Art & Design,"May 28, 2018",1.0,2.3 and up
3982,Cardi B Wallpaper,ART_AND_DESIGN,4.8,253,3.7M,"50,000+",Free,0,Everyone,Art & Design,"November 1, 2017",1.0.0,4.0 and up
4193,صور حرف H,ART_AND_DESIGN,4.4,13,4.5M,"1,000+",Free,0,Everyone,Art & Design,"March 27, 2018",2.0,4.0.3 and up
4241,Textgram - write on photos,ART_AND_DESIGN,4.4,295237,Varies with device,"10,000,000+",Free,0,Everyone,Art & Design,"July 30, 2018",Varies with device,Varies with device
4749,X Launcher: With OS11 Style Theme & Control Ce...,ART_AND_DESIGN,4.7,5754,4.4M,"100,000+",Free,0,Everyone,Art & Design,"July 30, 2018",2.1.2,4.1 and up
5179,Ai illustrator viewer,ART_AND_DESIGN,3.4,486,5.9M,"100,000+",Free,0,Everyone,Art & Design,"July 26, 2018",5.7,5.0 and up
5254,AJ Styles HD Wallpapers,ART_AND_DESIGN,4.8,48,25M,"5,000+",Free,0,Everyone,Art & Design,"August 4, 2018",1.1.1,4.1 and up
5258,AJ Styles Wallpaper 2018 - AJ Styles HD Wallpaper,ART_AND_DESIGN,4.0,18,3.6M,"1,000+",Free,0,Everyone,Art & Design,"March 22, 2018",1.1,4.0 and up
6930,Fantasy theme dark bw black building,ART_AND_DESIGN,4.8,41,1.9M,"5,000+",Free,0,Everyone,Art & Design,"March 20, 2018",1.0.2,4.0 and up
8679,Dp for girls,ART_AND_DESIGN,4.2,175,8.2M,"50,000+",Free,0,Everyone,Art & Design,"May 26, 2017",1.2,4.0.3 and up
8712,Name Art DP - Focus n Filter Text 2018,ART_AND_DESIGN,4.3,132,7.7M,"10,000+",Free,0,Everyone,Art & Design,"January 4, 2018",1,4.1 and up
8888,Spring flowers theme couleurs d t space,ART_AND_DESIGN,5.0,1,2.9M,100+,Free,0,Everyone,Art & Design,"April 18, 2018",1.0.2,4.0 and up

In [ ]:
### Q-how may free apps are avaliable in ART_AND_DESIGN with rating more than 4.5

In [111]:
highratingapps = freeapps[freeapps['Rating']>4.5]
print("ART_AND_DESIGN with rating more than 4.5",highratingapps)
highratingapps

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,121,3.1M,"10,000+",Free,0,Everyone,Art & Design;Creativity,"July 3, 2018",2.8,4.0.3 and up
13,Mandala Coloring Book,ART_AND_DESIGN,4.6,4326,21M,"100,000+",Free,0,Everyone,Art & Design,"June 26, 2018",1.0.4,4.4 and up
16,Photo Designer - Write your name with shapes,ART_AND_DESIGN,4.7,3632,5.5M,"500,000+",Free,0,Everyone,Art & Design,"July 31, 2018",3.1,4.1 and up
17,350 Diy Room Decor Ideas,ART_AND_DESIGN,4.5,27,17M,"10,000+",Free,0,Everyone,Art & Design,"November 7, 2017",1.0,2.3 and up
19,ibis Paint X,ART_AND_DESIGN,4.6,224399,31M,"10,000,000+",Free,0,Everyone,Art & Design,"July 30, 2018",5.5.4,4.1 and up
22,Superheroes Wallpapers | 4K Backgrounds,ART_AND_DESIGN,4.7,7699,4.2M,"500,000+",Free,0,Everyone 10+,Art & Design,"July 12, 2018",2.2.6.2,4.0.3 and up
24,HD Mickey Minnie Wallpapers,ART_AND_DESIGN,4.7,118,23M,"50,000+",Free,0,Everyone,Art & Design,"July 7, 2018",1.1.3,4.1 and up
25,Harley Quinn wallpapers HD,ART_AND_DESIGN,4.8,192,6.0M,"10,000+",Free,0,Everyone,Art & Design,"April 25, 2018",1.5,3.0 and up
26,Colorfit - Drawing & Coloring,ART_AND_DESIGN,4.7,20260,25M,"500,000+",Free,0,Everyone,Art & Design;Creativity,"October 11, 2017",1.0.8,4.0.3 and up
32,Anime Manga Coloring Book,ART_AND_DESIGN,4.5,5035,11M,"100,000+",Free,0,Everyone,Art & Design,"July 19, 2018",2.20,4.0 and up
34,I Creative Idea,ART_AND_DESIGN,4.7,353,4.2M,"10,000+",Free,0,Teen,Art & Design,"April 27, 2018",1.6,4.1 and up
36,UNICORN - Color By Number & Pixel Art Coloring,ART_AND_DESIGN,4.7,8145,24M,"500,000+",Free,0,Everyone,Art & Design;Creativity,"August 2, 2018",1.0.9,4.4 and up
38,PIP Camera - PIP Collage Maker,ART_AND_DESIGN,4.7,158,11M,"10,000+",Free,0,Everyone,Art & Design,"November 29, 2017",1.3,4.0.3 and up
41,Sad Poetry Photo Frames 2018,ART_AND_DESIGN,4.5,176,10M,"100,000+",Free,0,Everyone,Art & Design,"April 2, 2018",1.0,4.0.3 and up
45,"Canva: Poster, banner, card maker & graphic de...",ART_AND_DESIGN,4.7,174531,24M,"10,000,000+",Free,0,Everyone,Art & Design,"July 31, 2018",1.6.1,4.1 and up
46,Install images with music to make video withou...,ART_AND_DESIGN,4.6,1070,26M,"100,000+",Free,0,Everyone,Art & Design,"November 14, 2017",1.6,4.1 and up
3982,Cardi B Wallpaper,ART_AND_DESIGN,4.8,253,3.7M,"50,000+",Free,0,Everyone,Art & Design,"November 1, 2017",1.0.0,4.0 and up
4749,X Launcher: With OS11 Style Theme & Control Ce...,ART_AND_DESIGN,4.7,5754,4.4M,"100,000+",Free,0,Everyone,Art & Design,"July 30, 2018",2.1.2,4.1 and up
5254,AJ Styles HD Wallpapers,ART_AND_DESIGN,4.8,48,25M,"5,000+",Free,0,Everyone,Art & Design,"August 4, 2018",1.1.1,4.1 and up
6930,Fantasy theme dark bw black building,ART_AND_DESIGN,4.8,41,1.9M,"5,000+",Free,0,Everyone,Art & Design,"March 20, 2018",1.0.2,4.0 and up
8888,Spring flowers theme couleurs d t space,ART_AND_DESIGN,5.0,1,2.9M,100+,Free,0,Everyone,Art & Design,"April 18, 2018",1.0.2,4.0 and up

# 'DataAnalysis using Grouping'

### Q-Name the Apps of ART_AND_DESIGN with rating more than 4.5 in ascending order with respective rating

In [119]:
highratingapps.sort_values(by = 'Rating', ascending= True)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
17,350 Diy Room Decor Ideas,ART_AND_DESIGN,4.5,27,17M,"10,000+",Free,0,Everyone,Art & Design,"November 7, 2017",1.0,2.3 and up
41,Sad Poetry Photo Frames 2018,ART_AND_DESIGN,4.5,176,10M,"100,000+",Free,0,Everyone,Art & Design,"April 2, 2018",1.0,4.0.3 and up
32,Anime Manga Coloring Book,ART_AND_DESIGN,4.5,5035,11M,"100,000+",Free,0,Everyone,Art & Design,"July 19, 2018",2.20,4.0 and up
19,ibis Paint X,ART_AND_DESIGN,4.6,224399,31M,"10,000,000+",Free,0,Everyone,Art & Design,"July 30, 2018",5.5.4,4.1 and up
13,Mandala Coloring Book,ART_AND_DESIGN,4.6,4326,21M,"100,000+",Free,0,Everyone,Art & Design,"June 26, 2018",1.0.4,4.4 and up
46,Install images with music to make video withou...,ART_AND_DESIGN,4.6,1070,26M,"100,000+",Free,0,Everyone,Art & Design,"November 14, 2017",1.6,4.1 and up
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,121,3.1M,"10,000+",Free,0,Everyone,Art & Design;Creativity,"July 3, 2018",2.8,4.0.3 and up
22,Superheroes Wallpapers | 4K Backgrounds,ART_AND_DESIGN,4.7,7699,4.2M,"500,000+",Free,0,Everyone 10+,Art & Design,"July 12, 2018",2.2.6.2,4.0.3 and up
16,Photo Designer - Write your name with shapes,ART_AND_DESIGN,4.7,3632,5.5M,"500,000+",Free,0,Everyone,Art & Design,"July 31, 2018",3.1,4.1 and up
26,Colorfit - Drawing & Coloring,ART_AND_DESIGN,4.7,20260,25M,"500,000+",Free,0,Everyone,Art & Design;Creativity,"October 11, 2017",1.0.8,4.0.3 and up
24,HD Mickey Minnie Wallpapers,ART_AND_DESIGN,4.7,118,23M,"50,000+",Free,0,Everyone,Art & Design,"July 7, 2018",1.1.3,4.1 and up
36,UNICORN - Color By Number & Pixel Art Coloring,ART_AND_DESIGN,4.7,8145,24M,"500,000+",Free,0,Everyone,Art & Design;Creativity,"August 2, 2018",1.0.9,4.4 and up
34,I Creative Idea,ART_AND_DESIGN,4.7,353,4.2M,"10,000+",Free,0,Teen,Art & Design,"April 27, 2018",1.6,4.1 and up
38,PIP Camera - PIP Collage Maker,ART_AND_DESIGN,4.7,158,11M,"10,000+",Free,0,Everyone,Art & Design,"November 29, 2017",1.3,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
4749,X Launcher: With OS11 Style Theme & Control Ce...,ART_AND_DESIGN,4.7,5754,4.4M,"100,000+",Free,0,Everyone,Art & Design,"July 30, 2018",2.1.2,4.1 and up
45,"Canva: Poster, banner, card maker & graphic de...",ART_AND_DESIGN,4.7,174531,24M,"10,000,000+",Free,0,Everyone,Art & Design,"July 31, 2018",1.6.1,4.1 and up
25,Harley Quinn wallpapers HD,ART_AND_DESIGN,4.8,192,6.0M,"10,000+",Free,0,Everyone,Art & Design,"April 25, 2018",1.5,3.0 and up
3982,Cardi B Wallpaper,ART_AND_DESIGN,4.8,253,3.7M,"50,000+",Free,0,Everyone,Art & Design,"November 1, 2017",1.0.0,4.0 and up
5254,AJ Styles HD Wallpapers,ART_AND_DESIGN,4.8,48,25M,"5,000+",Free,0,Everyone,Art & Design,"August 4, 2018",1.1.1,4.1 and up
6930,Fantasy theme dark bw black building,ART_AND_DESIGN,4.8,41,1.9M,"5,000+",Free,0,Everyone,Art & Design,"March 20, 2018",1.0.2,4.0 and up
8888,Spring flowers theme couleurs d t space,ART_AND_DESIGN,5.0,1,2.9M,100+,Free,0,Everyone,Art & Design,"April 18, 2018",1.0.2,4.0 and up

In [120]:
#top 5 records
highratingapps.sort_values(by = 'Rating', ascending= True).head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
17,350 Diy Room Decor Ideas,ART_AND_DESIGN,4.5,27,17M,"10,000+",Free,0,Everyone,Art & Design,"November 7, 2017",1.0,2.3 and up
41,Sad Poetry Photo Frames 2018,ART_AND_DESIGN,4.5,176,10M,"100,000+",Free,0,Everyone,Art & Design,"April 2, 2018",1.0,4.0.3 and up
32,Anime Manga Coloring Book,ART_AND_DESIGN,4.5,5035,11M,"100,000+",Free,0,Everyone,Art & Design,"July 19, 2018",2.20,4.0 and up
19,ibis Paint X,ART_AND_DESIGN,4.6,224399,31M,"10,000,000+",Free,0,Everyone,Art & Design,"July 30, 2018",5.5.4,4.1 and up

### Q-Name the Apps of ART_AND_DESIGN with rating more than 4.5 in descending order with respective rating

In [121]:
highratingapps.sort_values(by = 'Rating', ascending= False).head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
8888,Spring flowers theme couleurs d t space,ART_AND_DESIGN,5.0,1,2.9M,100+,Free,0,Everyone,Art & Design,"April 18, 2018",1.0.2,4.0 and up
25,Harley Quinn wallpapers HD,ART_AND_DESIGN,4.8,192,6.0M,"10,000+",Free,0,Everyone,Art & Design,"April 25, 2018",1.5,3.0 and up
3982,Cardi B Wallpaper,ART_AND_DESIGN,4.8,253,3.7M,"50,000+",Free,0,Everyone,Art & Design,"November 1, 2017",1.0.0,4.0 and up
5254,AJ Styles HD Wallpapers,ART_AND_DESIGN,4.8,48,25M,"5,000+",Free,0,Everyone,Art & Design,"August 4, 2018",1.1.1,4.1 and up
6930,Fantasy theme dark bw black building,ART_AND_DESIGN,4.8,41,1.9M,"5,000+",Free,0,Everyone,Art & Design,"March 20, 2018",1.0.2,4.0 and up

### Q-which category has the maximun rating

In [128]:
df.groupby('Category').mean(numeric_only=True)['Rating'].sort_values(ascending=False)

Category
EVENTS                 4.435556
EDUCATION              4.389032
ART_AND_DESIGN         4.377049
BOOKS_AND_REFERENCE    4.346067
PERSONALIZATION        4.335256
PARENTING              4.300000
GAME                   4.286326
BEAUTY                 4.278571
HEALTH_AND_FITNESS     4.277104
SHOPPING               4.259664
SOCIAL                 4.255598
WEATHER                4.244000
SPORTS                 4.223511
PRODUCTIVITY           4.211396
HOUSE_AND_HOME         4.197368
FAMILY                 4.192383
PHOTOGRAPHY            4.192114
AUTO_AND_VEHICLES      4.190411
MEDICAL                4.189143
LIBRARIES_AND_DEMO     4.179688
FOOD_AND_DRINK         4.166972
COMMUNICATION          4.158537
COMICS                 4.155172
NEWS_AND_MAGAZINES     4.132189
FINANCE                4.131889
ENTERTAINMENT          4.126174
BUSINESS               4.121452
TRAVEL_AND_LOCAL       4.109292
LIFESTYLE              4.094904
VIDEO_PLAYERS          4.063750
MAPS_AND_NAVIGATION    4.051613
TOOLS                  4.047203
DATING                 3.970769
Name: Rating, dtype: float64